<?php
return [
    '+63' => '🇵🇭 Philippines',
    '+1'  => '🇺🇸 USA/Canada',
    '+44' => '🇬🇧 UK',
    '+61' => '🇦🇺 Australia',
    '+65' => '🇸🇬 Singapore',
    '+81' => '🇯🇵 Japan',
    '+971'=> '🇦🇪 UAE',
    '+966'=> '🇸🇦 Saudi Arabia',
    '+852'=> '🇭🇰 Hong Kong',
    '+886'=> '🇹🇼 Taiwan',
    '+82' => '🇰🇷 South Korea',
    '+60' => '🇲🇾 Malaysia',
    '+66' => '🇹🇭 Thailand',
    '+62' => '🇮🇩 Indonesia',
    '+84' => '🇻🇳 Vietnam',
    '+39' => '🇮🇹 Italy',
    '+33' => '🇫🇷 France',
    '+49' => '🇩🇪 Germany',
    '+34' => '🇪🇸 Spain',
    '+41' => '🇨🇭 Switzerland',
    '+351'=> '🇵🇹 Portugal',
    '+31' => '🇳🇱 Netherlands',
    '+32' => '🇧🇪 Belgium',
    '+43' => '🇦🇹 Austria',
    '+46' => '🇸🇪 Sweden',
    '+47' => '🇳🇴 Norway',
    '+45' => '🇩🇰 Denmark',
    '+353'=> '🇮🇪 Ireland',
    '+64' => '🇳🇿 New Zealand',
    '+91' => '🇮🇳 India',
    '+86' => '🇨🇳 China',
    '+7'  => '🇷🇺 Russia',
    '+52' => '🇲🇽 Mexico',
    '+974'=> '🇶🇦 Qatar',
    '+965'=> '🇰🇼 Kuwait'
];