<?php 
require_once __DIR__ . '/partials/header.php'; 
?>
<link rel="stylesheet" href="css/print.css">

<?php
$success = null;
$error = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['submit_contact'])) {
    $subject = $_POST['subject'] ?? 'Attendance Record Discrepancy';
    $messageBody = nl2br(htmlspecialchars($_POST['message'] ?? ''));
    $reportDate = date('F j, Y, g:i a'); 
    $userModel = new User();
    $userData = $userModel->findUserById($_SESSION['user_id']);
    $userFullName = $_SESSION['full_name'] ?? ($userData['first_name'] . ' ' . $userData['last_name']);
    $userEmail = !empty($userData['email']) ? $userData['email'] : 'No Email Found in Database';

    $fullContent = "
    <div style='font-family: \"Inter\", Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; color: #1e293b;'>
        <div style='background-color: #059669; padding: 25px; text-align: center;'>
            <h1 style='color: #ffffff; margin: 0; font-size: 20px; letter-spacing: 1px;'>BPC ATTENDANCE SYSTEM</h1>
            <p style='color: #ffffff; margin: 5px 0 0; font-size: 14px; font-weight: 700;'>Personnel Discrepancy Report</p>
        </div>
        
        <div style='padding: 30px; background-color: #ffffff;'>
            <p style='font-size: 16px; line-height: 1.6;'>A new attendance discrepancy has been reported. Please review the details below:</p>
            
            <table style='width: 100%; border-collapse: collapse; margin: 20px 0;'>
                <tr>
                    <td style='padding: 10px; background-color: #f8fafc; border: 1px solid #e2e8f0; font-weight: 700; width: 35%;'>Submitter</td>
                    <td style='padding: 10px; border: 1px solid #e2e8f0;'>{$userFullName}</td>
                </tr>
                <tr>
                    <td style='padding: 10px; background-color: #f8fafc; border: 1px solid #e2e8f0; font-weight: 700;'>Email Address</td>
                    <td style='padding: 10px; border: 1px solid #e2e8f0; color: #2563eb; font-weight: 600;'>{$userEmail}</td>
                </tr>
                <tr>
                    <td style='padding: 10px; background-color: #f8fafc; border: 1px solid #e2e8f0; font-weight: 700;'>Reported On</td>
                    <td style='padding: 10px; border: 1px solid #e2e8f0;'>{$reportDate}</td>
                </tr>
            </table>

            <div style='background-color: #fffbeb; border-left: 4px solid #f59e0b; padding: 20px; border-radius: 4px; margin-top: 25px;'>
                <h4 style='margin: 0 0 10px 0; color: #92400e; font-size: 14px; text-transform: uppercase;'>Description:</h4>
                <p style='margin: 0; font-size: 15px; color: #475569; font-style: italic; line-height: 1.6;'>\"{$messageBody}\"</p>
            </div>
        </div>

        <div style='background-color: #f1f5f9; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0;'>
            <p style='margin: 0; font-size: 12px; color: #64748b;'>This is an automated report generated by the BPC Attendance Management System.</p>
            <p style='margin: 5px 0 0; font-size: 12px; color: #64748b;'>IT Administration Department &copy; " . date('Y') . "</p>
        </div>
    </div>";

    $adminEmail = getenv('SMTP_USER');
    if (Mailer::send($adminEmail, $subject, $fullContent)) {
        $success = "Your discrepancy report has been sent to the IT Department.";
    } else {
        $error = "Failed to send report. Please visit the IT office directly.";
    }
}

$current_role = $_SESSION['role'] ?? 'staff'; 
$current_user_id = $_SESSION['user_id'] ?? 0;

$date_filter = "DATE(timestamp) = CURDATE()";

if ($isAdmin) {
    $user_filter = "1=1"; 
} else {
    $user_filter = "user_id = " . intval($current_user_id);
    $filters['start_date'] = date('Y-m-d');
    $filters['end_date'] = date('Y-m-d');
}
?>

<style>
.report-stats-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
    gap: 1.5rem;
    margin: 0 0 2rem 0;
    width: 100%;
}

.report-stat-card {
    background: #fff;
    padding: 1.5rem;
    border-radius: 12px;
    display: flex;
    align-items: center;
    gap: 20px;
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
    border: 1px solid transparent;
    cursor: pointer;
    transition: all 0.3s ease;
}

.report-stat-card:hover {
    transform: translateY(-5px);
    box-shadow: 0 12px 24px rgba(0,0,0,0.08);
    border-color: rgba(99, 102, 241, 0.2);
}

.report-stat-card:active { 
    transform: translateY(-2px); 
}

.stat-icon-bg {
    width: 60px;
    height: 60px;
    border-radius: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 1.5rem;
    flex-shrink: 0;
}

.stat-content {
    display: flex;
    flex-direction: column;
}

.stat-label {
    font-size: 0.875rem;
    color: #64748b;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.025em;
}

.stat-value {
    font-size: 1.875rem;
    font-weight: 700;
    color: #1e293b;
    line-height: 1;
    margin-top: 4px;
}

.attendance-table-new th, 
.attendance-table-new td {
    text-align: center !important;
    vertical-align: middle !important;
    padding: 12px !important;
}

.attendance-table-new tbody tr.accordion-toggle:nth-child(4n+1) { 
    background-color: #ffffff; 
}

.attendance-table-new tbody tr.accordion-toggle:nth-child(4n+3) { 
    background-color: #f8fafc; 
}

.attendance-table-new tbody tr.accordion-toggle:hover { 
    background-color: #f1f5f9 !important; 
}

.session-pill {
    background: #eff6ff;
    color: #2563eb;
    padding: 6px 12px;
    border-radius: 6px;
    font-weight: 700;
    font-size: 0.85rem;
    border: 1px solid #bfdbfe;
    display: inline-block;
    transition: all 0.2s ease;
}

.session-pill:hover {
    background: #dbeafe;
    border-color: #3b82f6;
}

.directory-table { 
    width: 100%; border-collapse: collapse; 
}

.directory-table th { 
    background: #f1f5f9; padding: 12px; text-align: center; font-size: 0.75rem; color: #475569; text-transform: uppercase; 
}

.directory-table td { 
    padding: 12px; border-bottom: 1px solid #f1f5f9; font-size: 0.9rem; text-align: center;
}

.btn-feedback {
    background: #4b5563;
    color: white;
    border-radius: 50px;
    padding: 8px 20px;
    font-weight: 600;
    transition: 0.3s;
}
.btn-feedback:hover { 
    background: #374151; 
}

#feedbackModal .modal-content {
    max-width: 550px;
    border-radius: 16px;
    border-top: 6px solid #059669;
}
.feedback-header-box {
    text-align: center;
    padding: 1.5rem 0;
    background: #f8fafc;
    border-radius: 12px;
    margin-bottom: 2rem;
}
.feedback-header-box i {
    font-size: 2.5rem;
    color: #059669;
    margin-bottom: 10px;
}
.feedback-textarea {
    min-height: 140px;
    border-radius: 10px;
    padding: 15px;
    border: 2px solid #e2e8f0;
    transition: border-color 0.2s;
}
.feedback-textarea:focus { 
    border-color: #059669; outline: none; 
}

#dtrPreviewModal .modal-content {
    max-width: 1400px;
    width: 98%;
    height: 96vh;
    margin: 2vh auto;
    display: flex;
    flex-direction: column;
    border-radius: 12px;
    border: none;
    box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.25);
}

#dtrPreviewModal .modal-header {
    background: #f8fafc;
    border-bottom: 1px solid #e2e8f0;
    padding: 1rem 1.5rem;
}

#dtrPreviewModal .modal-body {
    flex: 1;
    padding: 0 !important;
    display: flex;
    overflow: hidden;
}

#dtrFrame {
    width: 100%;
    height: 100%;
    border: none;
    background: #fff;
}

#dtrPreviewModal .modal-footer {
    background: #f8fafc;
    border-top: 1px solid #e2e8f0;
    padding: 1rem 1.5rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.stylish-input:hover { 
    border-color: #cbd5e1 !important; 
    background: #fff !important; 
}

.stylish-input:focus { 
    border-color: #6366f1 !important; background: #fff !important; 
    box-shadow: 0 0 0 4px rgba(99, 102, 241, 0.1) !important; 
}
    
.action-btn:hover { 
    transform: translateY(-1px); 
    filter: brightness(105%); 
    box-shadow: 0 4px 12px rgba(0,0,0,0.1); 
}

.action-btn:active { 
    transform: translateY(0); 
}
    
.date-field::-webkit-calendar-picker-indicator { 
    cursor: pointer; 
    filter: opacity(0.6) sepia(100%) saturate(200%) hue-rotate(190deg); 
}

</style>

<div class="main-body attendance-reports-page"> 
    <div class="info-card-header" style="background: linear-gradient(135deg, #1e293b 0%, #334155 100%); color: white; padding: 1.5rem; border-radius: 12px; margin-bottom: 2rem; display: flex; align-items: center; gap: 20px;">
        <div style="background: rgba(255,255,255,0.1); width: 60px; height: 60px; border-radius: 12px; display: flex; align-items: center; justify-content: center; font-size: 1.8rem;">
            <i class="fa-solid <?= $isAdmin ? 'fa-chart-line' : 'fa-user-clock' ?>"></i>
        </div>
        <div style="text-align: left;">
            <h2 style="margin: 0; font-size: 1.5rem; font-weight: 700;">
                <?= $isAdmin ? 'Personnel Attendance Reports' : 'My Personal Attendance' ?>
            </h2>
            <p style="margin: 5px 0 0; opacity: 0.8; font-size: 0.9rem;">
                <?= $isAdmin ? 'Manage personnel logs and generate administrative time records.' : 'Monitor your daily logs and track your attendance performance.' ?>
            </p>
        </div>
    </div>

    <div class="report-stats-grid">
        <div class="report-stat-card" onclick="openAttendanceDetail('entries', '<?= $isAdmin ? 'Total Entries Today' : 'My Entries Today' ?>')">
            <div class="stat-icon-bg bg-emerald-100 text-emerald-600"><i class="fa-solid fa-door-open"></i></div>
            <div class="stat-content">
                <span class="stat-label"><?= $isAdmin ? 'Entries Today' : 'My Entries Today' ?></span>
                <span class="stat-value"><?= $stats['entries'] ?? 0 ?></span>
            </div>
        </div>
        <div class="report-stat-card" onclick="openAttendanceDetail('exits', '<?= $isAdmin ? 'Total Exits Today' : 'My Exits Today' ?>')">
            <div class="stat-icon-bg bg-red-100 text-red-600"><i class="fa-solid fa-door-closed"></i></div>
            <div class="stat-content">
                <span class="stat-label"><?= $isAdmin ? 'Exits Today' : 'My Exits Today' ?></span>
                <span class="stat-value"><?= $stats['exits'] ?? 0 ?></span>
            </div>
        </div>
        <?php if ($isAdmin): ?>
        <div class="report-stat-card" onclick="openAttendanceDetail('present', 'Personnel On-Site')">
            <div class="stat-icon-bg bg-blue-100 text-blue-600"><i class="fa-solid fa-user-check"></i></div>
            <div class="stat-content">
                <span class="stat-label">Presents Today</span>
                <span class="stat-value"><?= $stats['present_total'] ?? 0 ?></span>
            </div>
        </div>
        <?php endif; ?>
        <div class="report-stat-card" onclick="openAttendanceDetail('late', '<?= $isAdmin ? 'Total Late Today' : 'My Late Arrivals' ?>')">
            <div class="stat-icon-bg bg-orange-100 text-orange-600"><i class="fa-solid fa-clock-rotate-left"></i></div>
            <div class="stat-content">
                <span class="stat-label"><?= $isAdmin ? 'Late Logs' : 'My Late Logs' ?></span>
                <span class="stat-value"><?= $stats['late'] ?? 0 ?></span>
            </div>
        </div>
    </div>

    <div style="display: flex; justify-content: flex-end; margin-bottom: 1.5rem; gap: 10px;">
        <a href="attendance_history.php" class="btn" style="background: #6366f1; color: white; border-radius: 50px; padding: 8px 20px; font-weight: 600; text-decoration: none;">
            <i class="fa-solid fa-clock-rotate-left"></i> Attendance History
        </a>
        <button class="btn btn-feedback" onclick="openModal('feedbackModal')">
            <i class="fa-solid fa-comment-dots"></i> Report Discrepancy
        </button>
    </div>

    <div class="filter-export-section card" style="border-radius: 16px; border: none; box-shadow: 0 4px 20px rgba(0,0,0,0.08); overflow: hidden; margin-bottom: 2rem;">
        <div class="card-header" style="background: #059669; border-bottom: none; padding: 1.25rem;">
            <h3 style="margin: 0; font-size: 1.1rem; color: #ffffff; font-weight: 700; display: flex; align-items: center; gap: 10px;">
                <i class="fa-solid fa-filter"></i> Filter & Reports
            </h3>
        </div>
        <div class="card-body" style="padding: 1.5rem; background: white;">
            <form method="GET" action="attendance_reports.php" id="reportFilterForm" style="display: flex; flex-wrap: wrap; align-items: flex-end; gap: 1.5rem;">
                <?php if ($isAdmin): ?>
                <div class="form-group" style="flex: 1; min-width: 200px; text-align: left;">
                    <label style="display: block; font-size: 0.75rem; font-weight: 800; color: #64748b; margin-bottom: 8px; text-transform: uppercase;">Select User</label>
                    <select name="user_id" id="userId" class="stylish-input" style="width: 100%; padding: 10px; border: 1.5px solid #e2e8f0; border-radius: 10px; background: #f8fafc;">
                        <option value="">-- Select User --</option>
                        <?php if (!empty($allUsers)): foreach ($allUsers as $user): ?>
                            <option value="<?= $user['id'] ?>" <?= (isset($filters['user_id']) && $filters['user_id'] == $user['id']) ? 'selected' : '' ?>>
                                <?= htmlspecialchars($user['first_name'] . ' ' . $user['last_name']) ?>
                            </option>
                        <?php endforeach; endif; ?>
                    </select>
                </div>
                <?php endif; ?>

                <div class="form-group" style="flex: 1.5; min-width: 280px; text-align: left;">
                    <label style="display: block; font-size: 0.75rem; font-weight: 800; color: #64748b; margin-bottom: 8px; text-transform: uppercase;">Date Range</label>
                    <div style="display: flex; gap: 8px; align-items: center;">
                        <input type="date" name="start_date" id="startDate" class="stylish-input date-field" value="<?= htmlspecialchars($filters['start_date'] ?? date('Y-m-01')) ?>" style="flex: 1; padding: 10px; border: 1.5px solid #e2e8f0; border-radius: 10px;">
                        <span style="color: #cbd5e1; font-weight: bold;">&rarr;</span>
                        <input type="date" name="end_date" id="endDate" class="stylish-input date-field" value="<?= htmlspecialchars($filters['end_date'] ?? date('Y-m-d')) ?>" style="flex: 1; padding: 10px; border: 1.5px solid #e2e8f0; border-radius: 10px;">
                    </div>
                </div>

                <div style="display: flex; gap: 10px;">
                    <button type="button" class="action-btn" onclick="handlePrintDTR()" style="padding: 11px 18px; background: #f59e0b; color: white; border: none; border-radius: 10px; font-weight: 600;">
                        <i class="fa-solid fa-file-invoice"></i> Generate DTR
                    </button>
                    <button type="submit" class="action-btn" style="padding: 11px 18px; background: #05865b; color: white; border: none; border-radius: 10px; font-weight: 600;">
                        <i class="fa-solid fa-check"></i> Apply Filter
                    </button>
                </div>
            </form>
        </div>
    </div>
    
    <div class="card attendance-table-card">
        <div class="card-body" style="padding: 0; overflow-x: auto;"> 
            <?php if (empty($records)): ?>
                <p style="text-align: center; color: #059669; padding: 40px;">No attendance records found.</p>
            <?php else: ?>
                <table class="attendance-table-new accordion-table" id="attendanceMainTable" style="min-width: 1000px; width: 100%;">
                    <thead>
                        <tr>
                            <th style="width: 50px;"></th>
                            <th>Faculty / Staff</th>
                            <th>Date</th>
                            <th>Duty Sessions</th>
                            <th>Final Status</th>
                        </tr>
                    </thead>
                    <tbody>
                    <?php $idx = 0; foreach ($records as $row): $idx++; ?>
                        <tr class="accordion-toggle" onclick="toggleAccordion('details-<?= $idx ?>', this)">
                            <td><i class="fa-solid fa-chevron-right toggle-icon"></i></td>
                            <td>
                                <div class="user-cell">
                                    <span class="user-name" style="font-weight:700; color:#1e293b;"><?= htmlspecialchars($row['name']) ?></span>
                                    <span class="user-id" style="display:block; font-size:0.75rem; color:#64748b;">ID: <?= htmlspecialchars($row['faculty_id']) ?></span>
                                </div>
                            </td>
                            <td><span class="date-cell"><?= date('M d, Y', strtotime($row['date'])) ?></span></td>
                            <td>
                                <span class="session-pill">
                                    <?php 
                                    $validScans = 0;
                                    foreach ($row['logs'] as $log) {
                                        $cols = ['am_in', 'am_out', 'pm_in', 'pm_out', 'time_in', 'time_out'];
                                        foreach ($cols as $c) {
                                            if (!empty($log[$c]) && $log[$c] != '00:00:00') { $validScans++; break; }
                                        }
                                    }
                                    echo $validScans;
                                    ?> Scan Record(s)
                                </span>
                            </td>
                            <td>
                                <span class="status-label status-<?= strtolower(str_replace(' ', '-', $row['status'])) ?>">
                                    <?= htmlspecialchars($row['status']) ?>
                                </span>
                            </td>
                        </tr>
                        
                        <tr id="details-<?= $idx ?>" class="accordion-content" style="display: none; background-color: #f8fafc;">
                            <td colspan="5" style="padding: 0;">
                                <div class="duty-breakdown-wrapper" style="padding: 20px 20px 20px 60px; text-align: left;">
                                    <h4 style="font-size: 0.9rem; color: #475569; margin-bottom: 15px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px;">
                                        <i class="fa-solid fa-fingerprint"></i> Duty Scan Breakdown
                                    </h4>

                                    <?php 
                                    $am_i = $am_o = $pm_i = $pm_o = null;

                                    foreach ($row['logs'] as $log) {
                                        if (!$am_i && !empty($log['am_in']) && $log['am_in'] != '00:00:00') {
                                            $am_i = strtotime($log['am_in']);
                                        }
                                        if (!$am_o && !empty($log['am_out']) && $log['am_out'] != '00:00:00') {
                                            $t_check = strtotime($log['am_out']);
                                            if (date('H:i', $t_check) !== date('H:i', $am_i)) $am_o = $t_check;
                                        }

                                        if (!$pm_i && !empty($log['pm_in']) && $log['pm_in'] != '00:00:00') {
                                            $pm_i = strtotime($log['pm_in']);
                                        }
                                        if (!$pm_o && !empty($log['pm_out']) && $log['pm_out'] != '00:00:00') {
                                            $t_check = strtotime($log['pm_out']);
                                            if (date('H:i', $t_check) !== date('H:i', $pm_i)) $pm_o = $t_check;
                                        }

                                        if (!$am_i && !$pm_i && !empty($log['time_in']) && $log['time_in'] != '00:00:00') {
                                            $t = strtotime($log['time_in']);
                                            if (date('H', $t) < 12) $am_i = $t; else $pm_i = $t;
                                        }
                                        
                                        if (!empty($log['time_out']) && $log['time_out'] != '00:00:00') {
                                            $t_out = strtotime($log['time_out']);
                                            if (date('H', $t_out) < 12) {
                                                if (!$am_o && date('H:i', $t_out) !== date('H:i', $am_i)) $am_o = $t_out;
                                            } else {
                                                if (!$pm_o && date('H:i', $t_out) !== date('H:i', $pm_i)) $pm_o = $t_out;
                                            }
                                        }
                                    }
                                    ?>

                                    <div class="scan-logs-grid" style="display: flex; gap: 15px; flex-wrap: wrap; justify-content: center;">
                                        <div class="scan-log-card" style="background: white; border: 1px solid #e2e8f0; border-left: 4px solid #059669; border-radius: 8px; padding: 12px; min-width: 220px;">
                                            <span style="font-size: 0.7rem; font-weight: 800; color: #059669; text-transform: uppercase;">
                                                <i class="fa-solid fa-sun"></i> Morning Session (AM)
                                            </span>
                                            <div style="display: flex; justify-content: space-between; margin-top: 8px; border-top: 1px dashed #f1f5f9; padding-top: 8px;">
                                                <div><small style="color: #94a3b8; display: block; font-size: 0.65rem;">ARRIVED</small><strong style="font-size: 1.1rem;"><?= $am_i ? date('g:i A', $am_i) : '--:--' ?></strong></div>
                                                <div><small style="color: #94a3b8; display: block; font-size: 0.65rem;">DEPARTED</small><strong style="font-size: 1.1rem;"><?= $am_o ? date('g:i A', $am_o) : '--:--' ?></strong></div>
                                            </div>
                                        </div>

                                        <div class="scan-log-card" style="background: white; border: 1px solid #e2e8f0; border-left: 4px solid #2563eb; border-radius: 8px; padding: 12px; min-width: 220px;">
                                            <span style="font-size: 0.7rem; font-weight: 800; color: #2563eb; text-transform: uppercase;">
                                                <i class="fa-solid fa-moon"></i> Afternoon Session (PM)
                                            </span>
                                            <div style="display: flex; justify-content: space-between; margin-top: 8px; border-top: 1px dashed #f1f5f9; padding-top: 8px;">
                                                <div><small style="color: #94a3b8; display: block; font-size: 0.65rem;">ARRIVED</small><strong style="font-size: 1.1rem;"><?= $pm_i ? date('g:i A', $pm_i) : '--:--' ?></strong></div>
                                                <div><small style="color: #94a3b8; display: block; font-size: 0.65rem;">DEPARTED</small><strong style="font-size: 1.1rem;"><?= $pm_o ? date('g:i A', $pm_o) : '--:--' ?></strong></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?> 
        </div> 
    </div> 
</div>

<div id="manualDtrModal" class="modal">
    <div class="modal-content" style="max-width: 550px; text-align: center; border-top: 5px solid #10b981;">
        <div class="modal-body" style="padding: 2.5rem;">
            <i class="fa-solid fa-clipboard-user" style="font-size: 3.5rem; color: #10b981; margin-bottom: 1rem;"></i>
            <h3 style="margin-bottom: 0.5rem; font-weight: 800;">Manual Record Entry</h3>
            <p style="color: #64748b; margin-bottom: 1.5rem;">Adding Manual Attendance Entry for <strong id="display_user_name" style="color: #1e293b;">---</strong>.</p>
            
            <form id="manualEntryForm" style="text-align: left;">
                <input type="hidden" id="manual_user_id">
                <div class="form-group mb-3">
                    <label style="font-size: 0.75rem; font-weight: 800; color: #64748b; text-transform: uppercase;">Date</label>
                    <input type="date" id="manual_date" class="form-control" style="width: 100%; border-radius: 8px; padding: 8px;" value="<?= date('Y-m-d') ?>">
                </div>

                <div class="row mb-3">
                    <div class="col-6">
                        <label style="font-size: 0.7rem; font-weight: 800; color: #059669; text-transform: uppercase;">AM In</label>
                        <input type="time" id="manual_am_in" class="form-control" style="border-radius: 8px; padding: 8px;">
                    </div>
                    <div class="col-6">
                        <label style="font-size: 0.7rem; font-weight: 800; color: #059669; text-transform: uppercase;">AM Out</label>
                        <input type="time" id="manual_am_out" class="form-control" style="border-radius: 8px; padding: 8px;">
                    </div>
                </div>

                <div class="row mb-4">
                    <div class="col-6">
                        <label style="font-size: 0.7rem; font-weight: 800; color: #2563eb; text-transform: uppercase;">PM In</label>
                        <input type="time" id="manual_pm_in" class="form-control" style="border-radius: 8px; padding: 8px;">
                    </div>
                    <div class="col-6">
                        <label style="font-size: 0.7rem; font-weight: 800; color: #2563eb; text-transform: uppercase;">PM Out</label>
                        <input type="time" id="manual_pm_out" class="form-control" style="border-radius: 8px; padding: 8px;">
                    </div>
                </div>

                <div style="display: flex; gap: 10px;">
                    <button type="button" class="btn btn-secondary w-50" onclick="closeModal('manualDtrModal')" style="padding: 12px; border-radius: 8px; font-weight: 600;">Cancel</button>
                    <button type="button" class="btn btn-primary w-50" onclick="submitManualDtr()" style="padding: 12px; border-radius: 8px; font-weight: 600; background: #10b981; border: none;">Save Record</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div id="selectionWarningModal" class="modal">
        <div class="modal-content" style="max-width: 420px; text-align: center; border-top: 5px solid #059669;">
            <div class="modal-body" style="padding: 2.5rem;">
                <i class="fa-solid fa-user-clock" style="font-size: 3.5rem; color: #059669; margin-bottom: 1rem;"></i>
                <h3 style="margin-bottom: 0.5rem; font-weight: 800;">Action Required</h3>
                <p style="color: #64748b; margin-bottom: 1.5rem;">To generate a Daily Time Record preview, please select a specific faculty member from the dropdown filter first.</p>
                <button class="btn btn-primary btn-full-width" onclick="closeModal('selectionWarningModal')" style="padding: 12px; border-radius: 8px; font-weight: 600;">Close & Select</button>
            </div>
        </div>
    </div>

    <div id="attendanceDetailModal" class="modal">
        <div class="modal-content" style="max-width: 900px; width: 95%;">
            <div class="modal-header">
                <h3 id="detailModalTitle">Attendance Details</h3>
                <button class="modal-close" onclick="closeModal('attendanceDetailModal')">&times;</button>
            </div>
            <div class="modal-body" id="detailModalBody" style="min-height: 200px; padding: 0;"></div>
            <div class="modal-footer">
                <button class="btn btn-secondary" onclick="closeModal('attendanceDetailModal')">Close</button>
            </div>
        </div>
    </div>

    <div id="dtrPreviewModal" class="modal">
        <div class="modal-content">
            <div class="modal-header" style="background: #f8fafc; border-bottom: 1px solid #e2e8f0;">
                <h3><i class="fa-solid fa-file-invoice"></i> CS Form 48 - DTR Preview</h3>
                <button class="modal-close" onclick="closeModal('dtrPreviewModal')">&times;</button>
            </div>
            <div class="modal-body" style="padding: 1rem; flex-grow: 1;">
                <iframe id="dtrFrame" src="about:blank"></iframe>
            </div>
            <div class="modal-footer" style="background: #f8fafc; border-top: 1px solid #e2e8f0; display: flex; justify-content: space-between;">
                <p style="font-size: 0.8rem; color: #64748b;">*This is a preview of your DTR Record. Print DTR by pressing the Print button at the top.</p>
            </div>
        </div>
    </div>
    
    <div id="feedbackModal" class="modal">
    <div class="modal-content modal-small">
        <div class="modal-header header-warning" style="background: #f59e0b;">
            <h3><i class="fa-solid fa-comment-dots"></i> Report Discrepancy</h3>
            <button type="button" onclick="closeFeedbackModal()" style="background:none; border:none; color:white; font-size:1.5rem; cursor:pointer;">&times;</button>
        </div>
        
        <form id="attendanceFeedbackForm">
            <div class="modal-body">
                <input type="hidden" name="submit_contact" value="1">
                <input type="hidden" name="subject" value="Attendance Record Discrepancy">
                
                <div style="background: #fffbeb; border: 1px solid #fef3c7; padding: 15px; border-radius: 10px; margin-bottom: 20px; display: flex; gap: 12px;">
                    <i class="fa-solid fa-circle-info" style="color: #d97706; font-size: 1.1rem; margin-top: 2px;"></i>
                    <p style="margin: 0; font-size: 0.85rem; color: #92400e; line-height: 1.5;">
                        Please specify the <strong>Date</strong> and <strong>Time</strong> of the error for verification.
                    </p>
                </div>

                <div class="form-group">
                    <label style="font-weight: 700; color: #475569; display: block; margin-bottom: 8px; font-size: 0.9rem;">Discrepancy Details</label>
                    <textarea name="message" class="form-control" rows="5" 
                        placeholder="Example: On Jan 22, my Time-Out shows as 4:30 PM instead of 5:00 PM..." 
                        required style="width: 100%; padding: 12px; border: 1.5px solid #e2e8f0; border-radius: 10px; resize: none;"></textarea>
                </div>
            </div>
            
            <div class="modal-footer">
                <button type="button" onclick="closeFeedbackModal()" class="btn btn-secondary w-50">Cancel</button>
                <button type="button" id="submitReportBtn" class="btn btn-primary w-50" style="background: #f59e0b; border: none;" onclick="handleAjaxSubmit()">
                    <i class="fa-solid fa-paper-plane"></i> Submit Report
                </button>
            </div>
        </form>
    </div>
</div>

    <div id="feedbackSuccessModal" class="modal">
        <div class="modal-content modal-small" style="text-align: center;">
            <div class="modal-body" style="padding: 3rem 1rem;">
                <i class="fa-solid fa-circle-check" style="font-size: 4rem; color: #10b981; margin-bottom: 1.5rem;"></i>
                <h3>Feedback Sent</h3>
                <p>The administrator has been notified. They will review your attendance logs shortly.</p>
                <button class="btn btn-primary" style="margin-top: 1.5rem;" onclick="closeModal('feedbackSuccessModal')">Got it</button>
            </div>
        </div>
    </div>

</div>

<div id="statusPopupModal" class="modal">
    <div class="modal-content modal-small" style="border-radius: 12px;">
        <div class="modal-header">
            <h3>Status Notification</h3>
            <button type="button" onclick="document.getElementById('statusPopupModal').style.display='none'; document.body.style.overflow='auto';" style="background:none; border:none; color:white; font-size:1.5rem; cursor:pointer;">&times;</button>
        </div>
        <div class="modal-body text-center" style="padding: 2.5rem 1.5rem;">
            <div class="status-icon-circle" style="width: 70px; height: 70px; border-radius: 50%; margin: 0 auto 20px; display: flex; align-items: center; justify-content: center; font-size: 30px;">
                <i class="fa-solid"></i>
            </div>
            <p id="statusModalMessage" style="color: #64748b; font-size: 0.95rem; line-height: 1.5; font-weight: 500;"></p>
        </div>
        <div class="modal-footer">
            <button onclick="document.getElementById('statusPopupModal').style.display='none'; document.body.style.overflow='auto';" class="btn btn-primary" style="min-width: 160px; border-radius: 8px;">
                Got it!
            </button>
        </div>
    </div>
</div>

<script>
document.addEventListener("DOMContentLoaded", function() {
    <?php if ($success || $error): ?>
        const statusModal = document.getElementById('statusPopupModal');
        if (statusModal) {
            statusModal.style.display = 'flex';
            document.body.style.overflow = 'hidden';
        }
    <?php endif; ?>
});
</script>

<script>
function filterTableRealTime() {
    const input = document.getElementById("liveSearchInput").value.toLowerCase();
    const rows = document.querySelectorAll("#attendanceMainTable tbody tr.accordion-toggle");

    rows.forEach(row => {
        const text = row.innerText.toLowerCase();
        const isMatch = text.includes(input);
        row.style.display = isMatch ? "" : "none";
        
        const detailId = row.getAttribute('onclick').match(/'([^']+)'/)[1];
        const detailRow = document.getElementById(detailId);
        if (detailRow) {
             detailRow.style.display = "none";
             row.classList.remove('active');
        }
    });
}

function handlePrintDTR() {
    const userIdInput = document.getElementById('userId');
    const userId = userIdInput ? userIdInput.value : '<?= $_SESSION['user_id'] ?>';
    const startDate = document.getElementById('startDate').value;
    const endDate = document.getElementById('endDate').value;

    if (!userId) {
        openModal('selectionWarningModal');
        return;
    }

    const url = `attendance_reports.php?action=print_dtr&user_id=${userId}&start_date=${startDate}&end_date=${endDate}`;
    document.getElementById('dtrFrame').src = url;
    openModal('dtrPreviewModal');
}

function openAttendanceDetail(type, title) {
    document.getElementById('detailModalTitle').innerText = title;
    document.getElementById('detailModalBody').innerHTML = '<div style="padding: 50px; text-align: center;"><i class="fa-solid fa-spinner fa-spin fa-2x"></i><p>Fetching records...</p></div>';
    openModal('attendanceDetailModal');

    fetch(`api.php?action=get_attendance_summary&type=${type}`)
        .then(res => res.json())
        .then(data => {
            if (data.success) {
                let html = '<table class="directory-table"><thead><tr><th>Faculty ID</th><th>Name</th><th>Position</th><th>Time</th></tr></thead><tbody>';
                data.users.forEach(u => {
                    html += `<tr>
                        <td style="font-weight:700;">${u.faculty_id}</td>
                        <td style="font-weight:600;">${u.first_name} ${u.last_name}</td>
                        <td><span class="ud-badge completed">${u.role}</span></td>
                        <td>${u.display_time}</td>
                    </tr>`;
                });
                if(data.users.length === 0) html += '<tr><td colspan="4" style="text-align:center; padding:40px; color:#94a3b8;">No records found for today.</td></tr>';
                html += '</tbody></table>';
                document.getElementById('detailModalBody').innerHTML = html;
            } else {
                document.getElementById('detailModalBody').innerHTML = `<p style="color:red; text-align:center; padding:20px;">${data.message}</p>`;
            }
        })
        .catch(err => {
            document.getElementById('detailModalBody').innerHTML = '<p style="color:red; text-align:center; padding:20px;">Connection Error.</p>';
        });
}

function renderAttendanceTable(users) {
    let html = `
        <table class="directory-table">
            <thead>
                <tr>
                    <th>Faculty ID</th>
                    <th>Name</th>
                    <th>Position</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>`;

    if (users.length === 0) {
        html += '<tr><td colspan="4" style="text-align:center; padding:40px; color:#94a3b8;">No records found for today.</td></tr>';
    } else {
        users.forEach(u => {
            let displayTime = u.timestamp ? new Date(u.timestamp).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'}) : '---';
            html += `
                <tr>
                    <td style="font-weight:700;">${u.faculty_id}</td>
                    <td style="font-weight:600;">${u.first_name} ${u.last_name}</td>
                    <td><span class="ud-badge completed">${u.role}</span></td>
                    <td>${displayTime}</td>
                </tr>`;
        });
    }
    html += '</tbody></table>';
    document.getElementById('detailModalBody').innerHTML = html;
}

function openFeedbackModal() {
    const modal = document.getElementById('feedbackModal');
    if (modal) {
        modal.style.display = 'flex';
        document.body.style.overflow = 'hidden';
    }
}

function closeFeedbackModal() {
    const modal = document.getElementById('feedbackModal');
    if (modal) {
        modal.style.display = 'none';
        document.body.style.overflow = 'auto';
    }
}

function openModal(id) {
    const modal = document.getElementById(id);
    if (modal) {
        modal.style.display = 'flex';
        document.body.style.overflow = 'hidden';
    }
}

function closeModal(id) {
    const modal = document.getElementById(id);
    if (modal) {
        modal.style.display = 'none';
        document.body.style.overflow = 'auto';
    }
}

window.onclick = function(event) {
    const feedbackModal = document.getElementById('feedbackModal');
    if (event.target == feedbackModal) {
        closeFeedbackModal();
    }
    if (event.target.classList.contains('modal')) {
        const id = event.target.id;
        closeModal(id);
        if(id === 'dtrPreviewModal') document.getElementById('dtrFrame').src = 'about:blank';
    }
}

function toggleAccordion(contentId, toggleEl) {
    const content = document.getElementById(contentId);
    const isVisible = content.style.display !== 'none';
    content.style.display = isVisible ? 'none' : 'table-row';
    toggleEl.classList.toggle('active');
}

window.closeDtrModal = function() {
    closeModal('dtrPreviewModal');
    document.getElementById('dtrFrame').src = 'about:blank';
};

function handleAjaxSubmit() {
    const form = document.getElementById('attendanceFeedbackForm');
    const btn = document.getElementById('submitReportBtn');
    
    if (!form.checkValidity()) {
        form.reportValidity();
        return;
    }

    btn.disabled = true;
    btn.innerHTML = '<i class="fa-solid fa-spinner fa-spin"></i> Sending...';

    const formData = new FormData(form);

    fetch('attendance_reports.php', {
        method: 'POST',
        body: formData
    })
    .then(response => {

        closeFeedbackModal();

        showStatusPopup("Report Submitted", "Your discrepancy report has been sent to the IT Department. Please wait for the official review.", "success");
    })
    .catch(error => {
        alert("Connection error. Please try again.");
    })
    .finally(() => {
        btn.disabled = false;
        btn.innerHTML = '<i class="fa-solid fa-paper-plane"></i> Submit Report';
    });
}

function showStatusPopup(title, message, type) {
    const modal = document.getElementById('statusPopupModal');
    const titleEl = modal.querySelector('h3');
    const messageEl = document.getElementById('statusModalMessage') || modal.querySelector('p');
    const iconContainer = modal.querySelector('.status-icon-circle');
    const icon = iconContainer.querySelector('i');

    titleEl.textContent = title;
    messageEl.textContent = message;

    if (type === 'success') {
        modal.querySelector('.modal-content').style.borderTop = "8px solid #10b981";
        iconContainer.style.background = "#ecfdf5";
        iconContainer.style.color = "#10b981";
        icon.className = "fa-solid fa-circle-check";
    } else {
        modal.querySelector('.modal-content').style.borderTop = "8px solid #ef4444";
        iconContainer.style.background = "#fef2f2";
        iconContainer.style.color = "#ef4444";
        icon.className = "fa-solid fa-circle-xmark";
    }

    modal.style.display = 'flex';
    document.body.style.overflow = 'hidden';
}
</script>

<?php require_once __DIR__ . '/partials/footer.php'?>